---
- name: Install ca-certificates package on Red Hat
  dnf:
    name: 
    - ca-certificates
    - openssl
    state: present

- name: Ensure trust directory exists (RedHat)
  file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory
    mode: 0755

...
